# Mongo credentials
MONGO:
  USER:
  PASSWORD:
  SERVER:
  PORT: 27017

# Server details
APP_SERVER:
  HOST: 0.0.0.0
  PORT: 9300


YOUTUBE:
  FETCH_API: https://www.googleapis.com/youtube/v3/search
  API_VERSION: v3
  API_KEYS: []

YOUTUBE_MONGO:
  DB_NAME: youtube_video_fetcher
  VIDEO_COLLECTION: video_data
  INDEX_COLLECTION: word_index_data


OLDEST_DATEIME: '2020-01-01T00:00:00Z'
ASYNC_INTERVAL: 10